version: '3.8'

services:
  app:
    build: .
    ports:
      - "5002:5002"
    depends_on:
      - db
    environment:
      - FLASK_ENV=production
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://user:password@db/ecommerce
      - PYTHONPATH=/app
      - FLASK_APP=app 
      - FLASK_DEBUG=True
      - SERVER_PORT=5002

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=ecommerce
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: